version: '3.9'
services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./src/backend
    container_name: api_contact
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      HOSTNAME: 127.0.0.1
      PORT_DB: 3306
      PORT: 3001
      JWT: secret
    ports:
      - 3001:3001
    command: npm start
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./src/frontend
    container_name: frontend_contact
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5